start filter
htmlacademy-javascript/199591-keksobooking-24 pull request #10
Opened 2021-11-07 20:04 UTC by MitKat

Привет! 
У меня очень сырой код, но застряла на проблеме и пока не решу  не навожу красоту.
Я сделала сортировку по типу жилья и вроде все хорошо работало, но точно такая сортировка по цене уже не работает, а по комнатам еще хуже. Не понимаю в чем может быть пролема.

2021-11-08 15:54 UTC, raccoonlemon requested changes
Ты кажется немного запуталась с фильтрацией и сортировкой.

В первую очередь нам нужно сделать фильтрацию. То что касается rank сюда не относится. Мы хотим выбрать предложения которые подходят под условия фильтров.

Сортировку можно сделать после. Там будет все что касается rank, но только после того как мы сделаем фильтрацию. По заданию мы сортируем по количеству features в каждом предложении. Т.е чем больше features - тем более подходящее предложение, отсортируем по убыванию и возьмем первые десять.

Нужно сделать какую-то функцию типа renderOffers. 

Функция  renderOffers будет делать следующее:
- брать все предложения которые мы получили с сервера (нужно их сохранить в переменную) 
- фильтровать их (с помощью getFilteredOffers)
- сортировать согласно rank 
- брать первые 10 штук из того что получилось
- отдавать то что в итоге получилось на отрисовку методу getBalun

В функцию getFilteredOffers мы передаем весь список предложений, которые пришли с сервера. В этой же функции мы можем проанализировать что у нас там заполнено в фильтре и с помощью метода массива filter проверить все эти условия и отобрать подходящие предложения.

На каждое поле фильтра событие onChange делать не обязательно, можно сделать целиком на форму фильтра - т.е применить делегирование. Все onChange для полей вызывают в итоге onChange на всю форму и там вызвать уже renderOffers.
Эту же функцию renderOffers можно вызвать после получения данных с сервера.

2021-11-11 13:09 UTC, MitKat commented on js/form-fiters.js
> +  // const selectedType = filtersType.value;
Вопрос. Что лучше для каждого значения заводить переменную и потом в сравнении использовать ее, но тогда кода больше. Или сразу в сравнении использовать filtersType.value? у меня сейчас второй вариант

2021-11-11 15:43 UTC, raccoonlemon requested changes
Уже почти хорошо =) 
Но есть что улучшить в плане читаемости кода.
И нет пока еще фильтра по features. По ним тоже нужно фильтровать.
А отсотировать уже просто в самом конце по offer.features.length

2021-11-11 15:43 UTC, raccoonlemon commented on js/form-fiters.js
> +  // const selectedType = filtersType.value;
У нас нет цели сделать поменьше кода =)
Главное - читаемость. Я бы переменную завела. Но не критично.

2021-11-11 15:43 UTC, raccoonlemon commented on js/form-fiters.js
> +};
Что-то оооочень замудреная штука sortFeatures. Мы для сортировки используем offers.features.length. Нам тут фильтр уже не нужен ведь.

2021-11-11 15:43 UTC, raccoonlemon commented on js/form-fiters.js
> +    .slice(0, SIMILAR_OFFER_COUNT);
Красивое =)

2021-11-11 15:43 UTC, raccoonlemon commented on js/form-fiters.js
> +  if (filtersPrice.value !== rangePrice && filtersPrice.value !== selectedStart) {
selectedStart=> ANY_VALUE

2021-11-11 15:43 UTC, raccoonlemon commented on js/form-fiters.js
> +  }
В константы надо будет вынести числа.
И можно немного с обратной стороны зайти - сделать константу PriceRange, где будет храниться тип и верхняя/нижняя границы.

2021-11-12 16:29 UTC, raccoonlemon approved these changes
Ты молодец!
По сортировке есть важное замечание, желательно поправить, но можно в следующем задании =)

2021-11-12 16:29 UTC, raccoonlemon commented on js/form-fiters.js
> +};
Можно порефакторить и упростить проверку на featuers. Если будет время и желание - можем над этим поработать.

2021-11-12 16:29 UTC, raccoonlemon commented on js/form-fiters.js
> +};
Если у нас нет offerA.offer.features, то подразумевается что их 0.
Иначе в случае если у нас функция не зайдет в условие, она вообще ничего не вернет, это неправильно.
Можно таким способом сделать
![image](https://user-images.githubusercontent.com/71271294/141499008-d1b5ad44-73f6-40ce-aa38-3c3ce06f9413.png)

2021-11-12 16:29 UTC, merged