add photo and avatar
htmlacademy-javascript/199591-keksobooking-24 pull request #11
Opened 2021-11-13 10:47 UTC by MitKat

2021-11-13 10:48 UTC, MitKat commented on js/photo-add.js
> +    if (photosPreview.length > MAX_VALUE_PHOTO) {
Вот тут момент, через remove у меня не получается пока, удалять просто одно изображение, и поэтому я всё очищаю, и начинаю заново добавлять....Если добавлять больше 4 фото они начинают выпадать из верстки

2021-11-13 11:33 UTC, raccoonlemon requested changes
Написала как фото жилья починить =)

2021-11-13 11:33 UTC, raccoonlemon commented on js/photo-add.js
> +    if (photosPreview.length > MAX_VALUE_PHOTO) {
Я так полагаю, там каждое фото должно быть в своей обертке, а не все картинки в одном 
`<div class="ad-form__photo"></div>.`

```
<div class="ad-form__photo">
      <img src="img/muffin-grey.svg" alt="Аватар пользователя" width="70" height="70">
</div>
<div class="ad-form__photo">
      <img src="img/muffin-grey.svg" alt="Аватар пользователя" width="70" height="70">
</div>
...

```
Вот я вручную вставила картинки прям в верстку. Кодом нужно такого же результата добиться.

![image](https://user-images.githubusercontent.com/71271294/141642172-2053dfdd-90fc-475a-a075-1476bc4e8301.png)

![image](https://user-images.githubusercontent.com/71271294/141642191-7b4fccd1-aa3c-4269-a60c-193dc17d49ec.png)

2021-11-13 11:33 UTC, raccoonlemon commented on js/photo-add.js
> +    if (photosPreview.length > MAX_VALUE_PHOTO) {
Еще нужно учесть, что когда нажимаем на Очистить форму, картинки тоже должны сброситься. Ну и после отправки на сервер тоже.

2021-11-14 12:05 UTC, raccoonlemon approved these changes
Теперь работает =)

2021-11-14 12:05 UTC, merged