started recording objects
htmlacademy-javascript/199591-keksobooking-24 pull request #3
Opened 2021-10-04 20:08 UTC by MitKat

2021-10-04 20:13 UTC, MitKat commented
У меня возникло много сомнений.
1. Объекты author, offer, location - должны быть созданы вне всех функций? 
2. а то я решила сделать одну функцию getInformation() . но споткнулась на том, что она должна возвращать - новый объект, со всеми теми же данными, как то странно...
3. где то по коду делала комментарии

2021-10-05 11:47 UTC, MitKat commented on js/main.js
> +
Вот функция getInformation(). Идея такая - мы в этой функции задаем все три объекта. На выходе должны получить объект с тремя ключами - autor, offer и location. Правильно?

2021-10-05 11:47 UTC, MitKat commented on js/main.js
> +    checkin: TIME[getRandomNumber(0, TIME.length-1)],
Или мы должны объекты вынести отдельно, чтобы вызывать по отдельности?
Но тогда вот такие вычисления случайных чисел и другие какие то вычисления будут нормальными?

2021-10-05 11:48 UTC, MitKat commented on js/main.js
> +  return console.log(Object.values(offer).join(', '));
ну и тут пока не поняла, как это все вернуть(

2021-10-05 12:17 UTC, raccoonlemon reviewed
> У меня возникло много сомнений.
> 
> 1. Объекты author, offer, location - должны быть созданы вне всех функций?
> 2. а то я решила сделать одну функцию getInformation() . но споткнулась на том, что она должна возвращать - новый объект, со всеми теми же данными, как то странно...
> 3. где то по коду делала комментарии

1-2. В каждом вызове функции getInformation будет создаваться свой  author, offer, location. И по итогу функции нам должен вернуться объект offer c полями: author, location и всеми прочими, типа room и т.д. Можешь для генерации автора и location сделать отдельные функции для наглядности типа getLocation и getAuthor, и вызывать их внутри getInformation

getInformation(){
const offer = {
   author: getAuthor()
   location: getLocation()
}
}

2021-10-05 12:17 UTC, raccoonlemon commented on js/main.js
> +    rooms: randomNumber,
Здесь можно делать так: 
price: getRandomNumber(300, 500)
guests: getRandomNumber(1, 5),
rooms: getRandomNumber(1, 4),

Тогда там будут разные значения. А то сейчас всем трем полям присваивается одно и то же значение.

2021-10-05 12:17 UTC, raccoonlemon commented on js/main.js
> +  };
Вот здесь все верно =)

2021-10-05 12:17 UTC, raccoonlemon commented on js/main.js
> +  return console.log(Object.values(offer).join(', '));
здесь просто написать return offer, тогда функция вернет тот объект который ты сгенерировала, и дальше по коду можно будет его использовать

2021-10-05 12:17 UTC, raccoonlemon commented on js/main.js
> +    type: TYPE[getRandomNumber(0, TYPE.length-1)],
Здесь тоже правильно. Но можно для этого сделать отдельную функцию-обертку типа:
getRandomArrayElement(array)

2021-10-05 12:23 UTC, raccoonlemon requested changes
Общее направление правильно. Написала комментарии по корректировкам. И еще не хватает пока всех необходимых полей в объекте offer.

2021-10-05 12:23 UTC, raccoonlemon commented on js/main.js
> +    address: location.lat, //не совсем понимаю, почему линт ругается
Проверила, странно, вроде не ругается.

2021-10-05 12:23 UTC, raccoonlemon commented on js/main.js
> +
Не совсем. Будет один объект offer, а author и location это поля этого объекта. Ну плюс все прочие необходимые поля.

2021-10-05 12:23 UTC, raccoonlemon commented on js/main.js
> +    checkin: TIME[getRandomNumber(0, TIME.length-1)],
Не совсем поняла вопрос. Но надеюсь другие комментарии помогут с этим разобраться =)

2021-10-09 20:17 UTC, MitKat commented on js/main.js
> +
Немного не поняла надо ли было сделать так, чтобы этот массив создавался автоматически, поэтому пока сделала в ручную.

2021-10-09 20:19 UTC, MitKat commented on js/main.js
> +  };
Вопрос?
Зачем нам нужен отдельно этот объект, если я в адрес могу также передать просто значения, а не данные из объекта?

2021-10-10 04:50 UTC, raccoonlemon requested changes
Все теперь в целом хорошо работает =)
По eslint несколько ошибок, и у меня по коду есть несколько небольших замечаний - обсудим все на консультации.

2021-10-10 04:50 UTC, raccoonlemon commented on js/main.js
> +
Чтобы потренироваться, можно сделать для avatarArchive в цикле заполнение. Но и так подойдет, тут не принципиально.

2021-10-10 04:50 UTC, raccoonlemon commented on js/main.js
> +  };
Он нам нужен для этого поля из задания:
![image](https://user-images.githubusercontent.com/71271294/136682341-1df11461-840f-4ad5-98a1-7e90ca5ddb77.png)

Т.е у нас в объекте offer который мы тут генерируем должно быть еще location.

2021-10-10 04:50 UTC, raccoonlemon commented on js/main.js
> +    address: location.lat + ' ' + location.lng,
Тут eslint нам говорит 
Unexpected string concatenation.
Операцию по конкатенации строк нужно делать через синтаксис шаблонной строки.
` address: `${location.lat} ${location.lng}``

2021-10-10 15:35 UTC, raccoonlemon approved these changes

2021-10-10 15:35 UTC, raccoonlemon commented on package.json
> +    "eslint-config-htmlacademy": "4.1.0"
Молодец, что обновила =)

2021-10-10 15:35 UTC, merged