work with the server
htmlacademy-javascript/199591-keksobooking-24 pull request #9
Opened 2021-11-04 21:41 UTC by MitKat

2021-11-04 21:46 UTC, MitKat commented on js/main.js
> +//сброс формы в начальное состояние
В целом все работает, разные ошибки проверяла. Но вот reset формы не знаю куда поставить. В form-offer не могу, так как из него передаю данные в map, а для reset мне нужны данные из map. Поэтому пока создала функцию, и работаю с ней в главном файле. По тем же причинам не могу на отправку формы сделать reset.

2021-11-04 21:48 UTC, MitKat commented on js/success-sent.js
> +  document.removeEventListener('keydown', onSuccessEscKeydown);
вопрос про удаление обработчика событий. плохо разобралась....удаляю только в этом файле обработчики....в других и не знаю, надо ли?

2021-11-05 05:24 UTC, raccoonlemon requested changes
Ты большая молодец =)
В целом очень здорово. Ответила на вопросы и замечания кое-где написала.
И есть проблема с внешним видом сообщения, т.к ты ему стили переопределила. Должно так выглядеть
![image](https://user-images.githubusercontent.com/71271294/140462563-cacfd1d0-ef9f-4db1-9205-6a9fa4bee6eb.png)

2021-11-05 05:24 UTC, raccoonlemon commented on js/success-sent.js
> +  successItem.style.height = 'auto';
А зачем тут стили вручную прописывать? В шаблоне же уже есть нужные классы.

2021-11-05 05:24 UTC, raccoonlemon commented on js/success-sent.js
> +  document.removeEventListener('keydown', onSuccessEscKeydown);
Событие 'click' можно повесить на само сообщение. Т.к. оно закрывает весь экран, то можно считать по нему клик.
В сообщении об ошибке есть кнопка - там на нее вешаем.
Когда мы закроем сообщение - все события которые на него были навешаны удалятся вместе с ним, самим удалять не нужно.


Удалять события нужно когда мы их вешаем на document. Иначе они там будут копиться, потому что будут добавляться при каждом появлении сообщения.

Можно проверять какие сейчас события есть в chrome dev tools - elements - event listeners. Если не удалять, то на document keydown можно будет увидеть что они копятся.

2021-11-05 05:24 UTC, raccoonlemon commented on js/success-sent.js
> +const successMain = document.querySelector('body');
successMain -> messageContainer

2021-11-05 05:24 UTC, raccoonlemon commented on js/utils/data.js
> +};
Сообщение из демо-проекта нам скорее всего не нужно.

2021-11-05 05:24 UTC, raccoonlemon commented on js/main.js
> +//сброс формы в начальное состояние
Нужно сделать свой метод resetForm в модуле form-offer. Туда не надо помещать resetMarker.
Полсе отправки можно вызвать
resetForm();
resteMarker();

resetForm() должен содержать сам сброс формы, и сброс выбранных координат.

Действия для кнопки "Очистить" тоже нужно самостоятельно определить. Она должна как данные формы сбрасывать, так и маркер.
Сброс маркера можно прокинуть в нее как коллбэк. Что-то вроде такого можно сделать

```
//main.js
setOnFormReset(resetMainMarker); // импорт из модуля формы

//form.js
const setOnFormReset = (callback)=>{
  form.querySelector('.ad-form__reset').addEventListener('click', (evt)=>{
    evt.preventDefault();
    resetForm();
    callback();
  });
};
```

2021-11-05 05:24 UTC, raccoonlemon commented on js/main.js
> +//сброс формы в начальное состояние
Там много разных вариантов, но основная идея - что можно прокинуть коллбэк. По принципу как ты делаешь для setFormSubmit.

2021-11-05 13:15 UTC, MitKat commented on js/utils/data.js
> +};
Я его использую в случае ошибки с сервера, если данные не придут. Думала по другому назвать, но потом решила просто воспользоваться из демо.

2021-11-05 13:15 UTC, MitKat commented on js/utils/api.js
> +    .then((tender) => {
Это я в какой то момент запуталась, в названиях и дала новое. Все исправлю

2021-11-05 13:16 UTC, MitKat commented on js/success-sent.js
> +  document.removeEventListener('keydown', onSuccessEscKeydown);
Спасибо, стало понятнее)

2021-11-05 17:34 UTC, raccoonlemon reviewed
Принято =)

2021-11-05 17:34 UTC, raccoonlemon commented on js/form-offer.js
> +  btnReset.addEventListener('click', (evt)=>{
Лучше не сокращать. Там по критерию может не пройти.
btnReset=>resetButton

2021-11-05 17:34 UTC, raccoonlemon approved these changes
Мелкое замечание по наименованию переменной. Остальное все хорошо.

2021-11-05 17:34 UTC, merged